automation:
  image: 'danelbert/docker-openhab:latest'
  ports:
    - '6300:8080'
  devices:
    - '/dev/ttyUSB0:/dev/ttyZwave0'
  volumes:
    - '/etc/openhab/configurations:/opt/openhab/configurations'
    - '/var/log/openhab:/opt/openhab/logs'
